### ISSUE TITLE
New to TripleGeo

### ISSUE THREAD

**Issue by Naurah** [GeoKnow/TripleGeo#8]
Hi.. Nice to meet u all.

I am new to this TripleGeo and currently doing my research on converting geospatial data or any other files to RDF data. I have read the Quick Start on How to Use Triple Geo here, but im still stuck. I dont understand how this tool will run in my laptop and how the RDF data will be look like.

Hopefully you guys can help me by explaining how this tool will works because im seriously have zero knowledge in it. Maybe with more detail explanation on how to start using this TripleGeo tool.

Thousands thank to you who are willing to help me.

**Comment by KostasPatroumpas** [comment]
Many thanks for your interest in our TripleGeo tool. Please check https://web.imis.athena-innovation.gr/redmine/projects/geoknow_public/wiki/TripleGeo for software architecture, detailed execution steps, and links to sample data.
